encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>" , views.entry, name = "title" ),
    path("search", views.search, name = "search"),
    path("create", views.create, name = "create"),
    path("edit/<str:title>", views.edit, name = "edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('encyclopedia/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms

from . import util
import random
import markdown2




class NewEntryForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control", 
                                                          "placeholder":"Title"}))
    text = forms.CharField(widget=forms.Textarea(attrs={'class': "form-control", 
                                                        "placeholder":"Content of the entry"}))

class EditForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': "form-control"}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    entry = util.get_entry(title)
    if  entry is not None:
        return render(request, "encyclopedia/entry.html",
            {"title" : title , "entry" : markdown2.markdown(entry)})

    return render(request, "encyclopedia/error.html", 
                {"title": title})

def search(request):
    if request.GET.get('title') is None:
        title = random.choice(util.list_entries())
        return HttpResponseRedirect(reverse("encyclopedia:title", kwargs={"title" : title}))

    else:
        title = request.GET.get('title')
        titles = util.list_entries()
        if title in titles:
            return HttpResponseRedirect(reverse("encyclopedia:title", kwargs={'title': title}))
        else:
            matches = [match for match in titles if title.lower() in match.lower()]
            return render(request, "encyclopedia/search_results.html",{"results": matches})
        
def create(request):
    if request.method == "POST":    
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title'] 
            if title not in util.list_entries():
                util.save_entry(title, form.cleaned_data['text'])
                return HttpResponseRedirect(reverse("encyclopedia:title", kwargs = {'title' : title}))
            else:
                form = NewEntryForm()
                return render(request,"encyclopedia/create.html",{"form":form, "message": True})
    
    else :
        form = NewEntryForm()
        return render(request,"encyclopedia/create.html",
                      {"form":form, "message": False})
    
def edit(request,title):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            util.save_entry(title, form.cleaned_data['text'])
            return HttpResponseRedirect(reverse("encyclopedia:title", kwargs = {'title' : title}))
    
    request.session['title'] = title
    form = EditForm({"text": util.get_entry(title)})
    return render(request, "encyclopedia/edit.html", context = {"form":form})

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
    <h1 class="display-3">Create a new entry</h1>
    {% if message %}
    <div class = "alert alert-warning col-lg-4" role="alert">
        The entry is already in the database.
        You can create a different one or edit the existing entry.
    </div>
    {% endif %}
    <form action = "{% url 'encyclopedia:create' %}" method="POST">
        <div class = "form-container">
            {% csrf_token %}
            {{form.title}}
            {{form.text}}
            <button type = "submit" class = "btn btn-primary">save</button>
        </div>
        
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% block body %}
    <h1 class = "display-5">Edit entry <em>"{{request.session.title}}".</em></h1>
    <form action = "{% url 'encyclopedia:edit' request.session.title%}" method="post">
        <div class = "form-container">
        {% csrf_token %}
        {{form.text}}
        <button type = "submit" class = "btn btn-primary">save</button>
        </div>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}{{title}}{% endblock %}
{% block body %}
{{entry | safe}}
<a style = "margin-top:15px; display:inline-block" href = "{% url 'encyclopedia:edit' title %}">edit</a>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Not found{% endblock %}
{% block body %}
    <h1 style = "font-family:Georgia, 'Times New Roman', Times, serif" >ERROR Entry {{title}} Not found</h1>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div style ="margin-left:15px">
        <h1 class = "display-3">All Pages</h1>

        <ul>
            {% for entry in entries %}
                <li><a href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}   

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    {% csrf_token %}
                    <input class="search" type="text" name="title" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:search' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}
{% block title %}results{% endblock %}
{% block body %}
    <h1 class = "display-5">The results for your search are:</h1>
    <ul>
    {% for res in results %}
        <li><a href="{% url 'encyclopedia:title' res%}">{{res}}</a></li>
    {% endfor %}
    </ul>
{% endblock %}